# Generated by Django 2.2.1 on 2019-10-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='key',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, choices=[('f', 'false'), ('w', 'waiting'), ('t', 'true')], max_length=100, null=True),
        ),
    ]
