# Generated by Django 2.2.1 on 2019-10-03 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20190930_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('gender', models.CharField(choices=[('f', 'female'), ('m', 'male')], max_length=2)),
            ],
            options={
                'ordering': ['row__number'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.Block')),
            ],
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['number']},
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('number',)},
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.Seat')),
            ],
            options={
                'ordering': ['number', 'seat__number'],
            },
        ),
        migrations.CreateModel(
            name='HallEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.Event')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.Hall')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.Row'),
        ),
        migrations.RemoveField(
            model_name='seat',
            name='block',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='row',
        ),
    ]
