# Generated by Django 2.2.1 on 2019-10-03 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20191003_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='row',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='block',
        ),
        migrations.RemoveField(
            model_name='row',
            name='seat',
        ),
        migrations.AddField(
            model_name='block',
            name='hall',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='ticket.Hall'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='row',
            name='block',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='ticket.Block'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='row',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='ticket.Row'),
            preserve_default=False,
        ),
    ]
