# Generated by Django 2.2.1 on 2019-10-03 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20191003_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticket.Hall'),
        ),
        migrations.AlterField(
            model_name='hallevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticket.Event'),
        ),
        migrations.AlterField(
            model_name='hallevent',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticket.Hall'),
        ),
        migrations.AlterField(
            model_name='row',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticket.Block'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticket.Price'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticket.Row'),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('name', 'gender', 'hall')},
        ),
        migrations.AlterUniqueTogether(
            name='row',
            unique_together={('number', 'block')},
        ),
    ]
