# Generated by Django 2.2.1 on 2019-10-04 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20191003_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={},
        ),
        migrations.AlterModelOptions(
            name='row',
            options={'ordering': ['block', 'number']},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['row', 'number']},
        ),
        migrations.AlterField(
            model_name='block',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.Hall'),
        ),
        migrations.AlterField(
            model_name='hallevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.Event'),
        ),
        migrations.AlterField(
            model_name='hallevent',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.Hall'),
        ),
        migrations.AlterField(
            model_name='row',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.Block'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seat', to='ticket.Ad'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat', to='ticket.Price'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.Row'),
        ),
        migrations.AlterField(
            model_name='userservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.Service'),
        ),
        migrations.AlterField(
            model_name='userservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('number', 'row')},
        ),
    ]
